src/init.py
Signed-off-by: Lisa Seelye <lseelye@redhat.com>
=> Check for the existance of annotations before accessing them

build/build_deploy.sh, build/pr_check.sh
Adding a pr check script and a build deploy script
=> Needing a build and pr check script added to the webhook repo

templates/10-group-validation.ValidatingWebhookConfiguration.yaml.tmpl
For 4.2 this must be Cluster scoped.
=> group validation must be Cluster-scoped

build/build_deploy.sh
=> Updating skopeo tagging

build/build_deploy.sh, build/selectorsyncset.yaml, templates/20-validation-webhook.deployment.yaml.tmpl
=> More updates to correctly generate selectorsyncset.yaml

build/build_deploy.sh
=> Updating tagging, removing version numbers

src/webhook/group_validation.py
https://issues.redhat.com/browse/OSD-2573
=> Allow system:admin to manage any groups

Makefile, src/webhook/__init__.py, src/webhook/namespace_validation.py, templates/10-namespace-validation.ValidatingWebhookConfiguration.yaml.tmpl
https://issues.redhat.com/browse/OSD-2744
=> OSD-2744 Added webhook validation for updating namespaces

build/selectorsyncset.yaml
Refreshing build/selectorsyncset.yaml
=> Fix build/selectorsyncset.yaml

src/webhook/group_validation.py
https://issues.redhat.com/browse/OSD-2923
=> Fix bug causing exceptions when trying to delete groups OSD-2923

build/selectorsyncset.yaml, templates/20-validation-webhook.deployment.yaml.tmpl
https://issues.redhat.com/browse/OSD-3126
=> Switch to deployments apps/v1

build/selectorsyncset.yaml, templates/20-validation-webhook.deployment.yaml.tmpl
https://issues.redhat.com/browse/OSD-3126
=> Added missing selector to deployment

Makefile, deploy/01-webhook.namespace.yaml, deploy/02-webhook-cacert.configmap.yaml, deploy/02-webhook.permissions.yaml, src/webhook/__init__.py, src/webhook/regular_user_validation.py, templates/10-regular-user-validation.ValidatingWebhookConfiguration.yaml.tmpl, templates/20-validation-webhook.deployment.yaml.tmpl
https://issues.redhat.com/browse/OSD-2686
=> Generic webhook that denies all requests to regular users

build/00-osd-managed-cluster-validating-webhooks.selectorsyncset.yaml.tmpl, build/selectorsyncset.yaml
https://issues.redhat.com/browse/OSD-3163
=> Use 'Sync' instead of 'sync' for resourceApplyMode

Makefile, build/build_deploy.sh, build/selectorsyncset.yaml, templates/20-validation-webhook.deployment.yaml.tmpl
Updated so it's generated by default when you build and fixed how it is generated.
=> Fixed generation of selectorsyncset

.gitignore, Makefile, build/Dockerfile.test, requirements.txt, src/webhook/regular_user_validation.py, src/webhook/test_regular_user_validation.py
https://issues.redhat.com/browse/OSD-3242
SRE is now allowed to modify the resources the regular user validation webhook gates.
Added unit tests for regular_user_validation (yay!)
Added generation of requirements.txt (just in case you need it)
=> Fix Bug: Regular-User validation webhook is treating SREs as regular users

build/selectorsyncset.yaml, src/webhook/__init__.py, src/webhook/identity_validation.py, src/webhook/test_identity_validation.py, src/webhook/test_user_validation.py, src/webhook/user_validation.py, templates/10-identity-validation.ValidatingWebhookConfiguration.yaml, templates/10-user-validation.ValidatingWebhookConfiguration.yaml
https://issues.redhat.com/browse/OSD-3271
=> Add validating webhook for user and identity

README.md, build/selectorsyncset.yaml, src/webhook/group_validation.py, src/webhook/namespace_validation.py, src/webhook/request_helper/validate.py, src/webhook/test_group_validation.py, src/webhook/test_namespace_validation.py, templates/20-validation-webhook.deployment.yaml.tmpl
Name                                          Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------
src/webhook/group_validation.py                  55     17    69%   22-40, 55, 59, 68
=> Add unit tests for group validation webhook OSD-3361

src/webhook/test_namespace_validation.py
Adding unit tests as part of OSD-3547
=> Adding unit tests

src/webhook/request_helper/validate.py
The "userInfo" is not part of the top level key, this will fail all the validations.
=> This fix the request validation issue

Makefile, src/gunicorn.py, src/webhook/group_validation.py, src/webhook/namespace_validation.py, src/webhook/request_helper/responses.py, src/webhook/subscription_validation.py, src/webhook/test_group_validation.py, src/webhook/user_validation.py
https://issues.redhat.com/browse/OSD-3511
blocks: https://issues.redhat.com/browse/INTLY-7632
Merges https://github.com/openshift/managed-cluster-validating-webhooks/pull/62
Fixes some validation holes
Adds some missing increment of deny counters (metrics)
A few lint fixes
Add 'lint' and 'test' make targets to default 'all' make target
=> Merge OSD-3511 changes

src/webhook/subscription_validation.py, src/webhook/test_subscription_validation.py
Name                                          Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------
src/webhook/subscription_validation.py           41     14    66%   20-38
=> Add unit tests for subscription_validation.py OSD-3364

pkg/webhooks/namespace/namespace.go, pkg/webhooks/namespace/namespace_test.go
Protecting the com, in, and io namespaces as part of OSD-4046
=> Initial effort at OSD-4046, protecting 3 additional namespaces

Makefile
Relates to #91, #87 (and #89).
The pipeline doesn't have `go` in it (and if it did, it wouldn't be guaranteed to be the version used herein), so build the syncset make target in a golang:1.14 container.
Other cosmetic fixes to the Makefile (white spacing, use of `$@`).
It is tempting to use `registry.svc.ci.openshift.org/openshift/release:golang-1.14` for the syncset target since that's the base image used in the `Dockerfile`, but in my testing that image did not work for this.
=> OSD-4391: Build syncset in Go container b/c pipeline lacks go

pkg/webhooks/user/user.go, pkg/webhooks/user/user_test.go
=> OSD-4391: IDPs are prefixes

pkg/webhooks/user/user.go
This PR is largely optional, but will increase visibility (and remove a dump of group memberships).
=> OSD-4391: Logging improvements

README.md
=> OSD-4519: How to delete or disable a webhook

README.md
https://issues.redhat.com/browse/OSD-5067
=> Document identity webhook e2e testing OSD-5067

pkg/webhooks/group/group.go, pkg/webhooks/identity/identity.go, pkg/webhooks/namespace/namespace.go, pkg/webhooks/regularuser/regularuser.go
=> OSD-5226: Improve denial messages for OSD customers

pkg/webhooks/namespace/namespace.go
See https://docs.google.com/spreadsheets/d/1sT3loQphcc75k3W3EKCcyeSTQ1ppK7Md7ASB0CUSOLQ/edit#gid=0
=> OSD-5377 Fine tune error messages for namespace webhook

pkg/webhooks/namespace/namespace.go, pkg/webhooks/namespace/namespace_test.go
Allow dedicated-admins to label customer namespaces while still
protecting quota-related labels (See
https://github.com/openshift/managed-cluster-config/tree/master/deploy/resource-quotas)
=> OSD-2019: Allow dedicated-admins to label namespaces

build/selectorsyncset.yaml, pkg/webhooks/add_hiveownership.go, pkg/webhooks/hiveownership/hiveownership.go, pkg/webhooks/hiveownership/hiveownership_test.go
Fixes: https://issues.redhat.com/browse/OSD-6180
osde2e: https://github.com/openshift/osde2e/pull/688
=> feat: add hiveownership webhook

build/selectorsyncset.yaml, pkg/webhooks/hiveownership/hiveownership.go
Fix: #131  
issue: hook was not getting triggered due to resource name mismatch
=> fix: hiveownership resources typo

README.md
...that I ran into while I was testing today.
=> More live testing details

pkg/webhooks/clusterlogging/clusterlogging.go, pkg/webhooks/clusterlogging/clusterlogging_test.go
* 1h <= app <= 7d
* infra == 1h
* audit == 1h
jira: [OSD-6701](https://issues.redhat.com/browse/OSD-6701)
=> Update retention policy boundaries

OWNERS
Add tnierman to reviewers/approvers.
=> Add tnierman to OWNERS

build/selectorsyncset.yaml, docs/webhooks-short.json, docs/webhooks.json, pkg/webhooks/add_scc.go, pkg/webhooks/scc/scc.go, pkg/webhooks/scc/scc_test.go
fixes [OSD-8315](https://issues.redhat.com/browse/OSD-8315)
=> add validation webhook for scc

pkg/webhooks/prometheusrule/prometheusrule.go
Per OSD-13680, adding a temporary exception to unblock AppSRE
=> Add exception for openshift-customer-monitoring for the PrometheusRule webhook

pkg/webhooks/imagecontentpolicies/imagecontentpolicies.go
[OSD-15757](https://issues.redhat.com//browse/OSD-15757)
We weren't registering the scheme and there were logical errors in the validation process
=> Fix bugs with icp webhook validation

OWNERS
* Adding regular contributers to the approvers list for higher review throughput
=> Add approvers

pkg/webhooks/imagecontentpolicies/imagecontentpolicies.go
This statement isn't exactly right. Updating it to be correct and slightly more generic.
=> OSD-17575: Update webhook docs for ICSPs

build/Dockerfile
Use latest ubi-minimal as current one has CVE's
=> Update ubi base image to remediate CVE's

config/package/resources.yaml.gotmpl
Resolves [OSD-18990](https://issues.redhat.com//browse/OSD-18990)
=> Deploy to non-request-serving nodes

build/resources.go
Resolves [OSD-18990](https://issues.redhat.com//browse/OSD-18990)
=> Add hypershift.openshift.io/control-plane toleration to resources.go

README.md, build/selectorsyncset.yaml, pkg/webhooks/add_ingressconfig_hook.go, pkg/webhooks/ingressconfig/ingressconfig.go, pkg/webhooks/ingressconfig/ingressconfig_test.go
re-add the ingress config webhook but this time allowing the system:admin user to modify ingress configs as well
=> Ingress config bugfix

build/Dockerfile
=> [OSD-19608] Updating base image

designs/validating_admission_policy.md
If there's agreement amongst approvers in this repo, the next step for this design will be an ADR.
=> Propose deprecating this repo and moving to ValidatingAdmissionPolicy

pkg/webhooks/prometheusrule/prometheusrule.go
https://issues.redhat.com/browse/OSD-19716
---
Adds a specific exception for ACS' components in preparation of https://issues.redhat.com/browse/OSD-13909, which will remove the namespace-wide exception for prometheusrule modification in `openshift-monitoring`. 
Due to technical limitations on the ACS-side, it's not reasonable for this component to deploy it's prometheusrules in a different namespace for the time being. https://issues.redhat.com/browse/OBSDA-555 has been created to construct a dedicated namespace for layered-products upstream, until it is complete we can minimize the gap in our webhooks by limiting creation to only those with ACS-specific labels.
=> OSD-19716 - Add ACS exception to MCVW

build/selectorsyncset.yaml, go.mod, pkg/webhooks/add_customresourcedefinitions.go, pkg/webhooks/customresourcedefinitions/customresourcedefinitions.go, pkg/webhooks/customresourcedefinitions/customresourcedefinitions_test.go, pkg/webhooks/utils/utils.go
Adds a validating webhook to block unpriviledged modifications of protected custom resource definitions while allowing modifications of unprotected ones.
=> [OSD-16432] Adds a validating webhook to block unpriviledged modifications of protected custom resource definitions

pkg/webhooks/networkpolicies/networkpolicies.go, pkg/webhooks/networkpolicies/networkpolicies_test.go
* Users need to be allowed to set networkpolicies for custom ingresses in namespace openshift-ingress
* Refactored the test since a lot of new CRUD tests had to be added to cover edge cases
Jira: [OSD-20308](https://issues.redhat.com//browse/OSD-20308)
=> Allow networkpolicy changes for custom ingress

build/resources.go, build/selectorsyncset.yaml, cmd/main.go
this will avoid clobbering the webhooks service
=> OSD-20191 use a separate svc for the metrics service

build/resources.go, build/selectorsyncset.yaml, cmd/main.go
ensure prometheus metrics are getting scraped
=> OSD-20191 ensure prometheus metrics are getting scraped

pkg/webhooks/node/node.go, pkg/webhooks/node/node_test.go
In this commit, I modified the node webhook to allow OSD and ROSA users to modify worker nodes.
https://issues.redhat.com/browse/OSD-20485
=> [OSD-20485]Updated node webhook to allow user to modify worker nodes

pkg/webhooks/node/node.go
In this commit, I added a deny policy for users deleting a worker node.
=> [OSD-20485]Added an explicit dent for users trying to delete a worker node

pkg/webhooks/node/node.go
[OSD-20485](https://issues.redhat.com//browse/OSD-20485)
=> Add log messages to the webhook to better understand its behavior

pkg/webhooks/node/node.go
We noticed when running `oc delete node ${node}`, these logs appeared in the webhook pod logs:
```
E0125 20:28:34.347118       1 node.go:147] "msg"="failed to render a Node from request" "error"="there is no content to decode" "logger"="node-validation-osd"
```
[OSD-20485](https://issues.redhat.com//browse/OSD-20485)
=> Move block on node deletion before attempting to decode request

pkg/webhooks/sdnmigration/sdnmigration.go, pkg/webhooks/sdnmigration/sdnmigration_test.go
Add a "red-hat-internal-testing": "true" override to disable the effects of this webhook.
The unit tests weren't working as intended because the decoder interacts with the `Raw` object inside of each admission requests's Object/OldObject so I fixed those up as well.
[OSD-20474](https://issues.redhat.com//browse/OSD-20474)
=> Better enable internal testing of SDN --> OVN

build/selectorsyncset.yaml, pkg/webhooks/regularuser/common/regularuser.go
ref [OSD-22474](https://issues.redhat.com//browse/OSD-22474)
=> Block changes to imageregistry.operator.openshift.io resources

pkg/webhooks/scc/scc.go, pkg/webhooks/scc/scc_test.go
Partial revert of #291
ref [OSD-21840](https://issues.redhat.com//browse/OSD-21840)
=> Remove osde2e exception from modifying SCCs

OWNERS
I regret that I don't have the time to stay as attached to mcvw as I was when I ported it from Python to Go, but the sad reality is, my time is just not as available as it once was. :(
=> Remove lisa as a reviewer in OWNERS

OWNERS
Add myself as a reviewer and approver to this repo.
=> Add joshbranham to approvers

pkg/webhooks/sdnmigration/sdnmigration.go
We are adding this change to ensure that hive is the one that can trigger the SDN to OVN network migration. 
Hive does not use a service account to connect to the cluster but a privilege admin user. 
Please Refer to [OSD-21711](https://issues.redhat.com//browse/OSD-21711)  for full explanation.
=> OSD-21711 check to allow hive admin user to trigger an SDN migration

osde2e/managed_cluster_validating_webhooks_test.go
What type of PR is this?
Test Update
What this PR does / why we need it?
This PR updates the test case for managed-cluster-validating-webhooks to enforce security context settings.
Which Jira/GitHub issue(s) this PR fixes?
Part of [OSD-28133](https://issues.redhat.com//browse/OSD-28133)
Special notes for your reviewer:
The test case now includes SecurityContext settings to enforce security policies.
This change is limited to test logic and does not affect operational code.
=> Update test case to enforce security context settings

test/e2e/project.mk, test/e2e/test-harness-template.yml
MCVW  is not boilerplated, so osde2e convention updates need to be done manually from 
https://github.com/openshift/boilerplate/tree/master/boilerplate/openshift/golang-osd-operator-osde2e
=> copying e2e suite update from boilerplate

test/e2e/managed_cluster_validating_webhooks_test.go
operators can run on non-infra nodes, there is no webhook for this
=> remove operators from webhook check

OWNERS
Add Thor as reviewer as Thor is maintaining IAM domain.
=> Add thor as reviewer

.github/renovate.json, .tekton/managed-cluster-validating-webhooks-pull-request.yaml, .tekton/managed-cluster-validating-webhooks-push.yaml, build/Dockerfile
Updating base image registry and renovate, on-cel expression changes.
=> Konflux managed cluster validating webhooks

test/e2e/validation_webhook_tests.go
This PR is related to https://issues.redhat.com/browse/SREP-1045, which is disabling the `"allows backplane-cluster-admin to manage MustGather CRs"` test case and should allow CI/CD to proceed with a build. 
This will be re-enabled once the MG operator is fixed.  
NOTE: more details are in https://redhat-internal.slack.com/archives/C0326L38PEH/p1755236121635909
=> [SREP-1045] Disabled e-2-e test due to missing MustGather CRD

.github/renovate.json, .tekton/managed-cluster-validating-webhooks-pull-request.yaml, .tekton/managed-cluster-validating-webhooks-push.yaml
Migrating operator from app interface to konflux.
As part of on migration,  name space and application  creation is completed  and initial image released in konflux.
This PR is to add on-cel expression changes to tekton files and Renovate changes.
=> OSD-30954 Update Renovate and on-cel expression changes

OWNERS
=> chore: Add team Thor as approvers
