openshift/managed-cluster-validating-webhooks

- README.md
- src/gunicorn.py
- src/webhook/__init__.py
- src/webhook/group_validation.py
- src/webhook/request_helper/validate.py
- src/webhook/subscription_validation.py
- templates/10-subscription-validation.ValidatingWebhookConfiguration.yaml.tmpl
- templates/20-validation-webhook.deployment.yaml.tmpl
This changeset adds a validation webhook using the same pattern as in #1
which will constrain dedicated-admins to making `Subscription` objects
whose `.spec.sourceNamespace` is defined in a comma-separated list from
the `SUBSCRIPTION_VALIDATION_N    AMESPACES` environment variable (By
default it is only the `openshift-operators` namespace whic is a
permitted `.spec.sourceNamespace` for dedicated-admins).
This changeset also makes some other structural changes:
* Move the environment variables relating to the webhooks out of the
gunicorn.py and into the `Deployment` spec (so that it makes more sense)
* Fundamental changes to the structure of the validation library so that
it is now only looking for the basic structure of the AdmissionReview
(does it have a `kind`? Is it `AdmissionReview`). …
> SREP-2239: Add Subscription validation

- src/webhook/group_validation.py
- src/webhook/subscription_validation.py
Moving to only `POST`, but keeping `('POST')` is evidently a syntax
error, so this has been fixed by using `['POST']`.
Signed-off-by: Lisa Seelye <lseelye@redhat.com>
> Fix broken HTTP methods declaration

- README.md
There are now more than one webhook, and so the removed reference no longer makes sense.
> Remove obsolete single webhook reference

- README.md
- src/webhook/group_validation.py
- templates/20-validation-webhook.deployment.yaml.tmpl
We may need to refactor this later to encapsulate more permissions, but
for now, kube:admin functions as "`root`", and can do anything.
Signed-off-by: Lisa Seelye <lseelye@redhat.com>
> SREP-2442: Allow kube:admin to create any group

- src/webhook/subscription_validation.py
- templates/20-validation-webhook.deployment.yaml.tmpl
Since all official CatalogSources/OperatorSources reside in the openshift-marketplace NS, update the safelisted NS for sourceNamespaces
> Replace safelisted NS for Subscriptions with openshift-marketplace NS

- src/requirements.txt
- src/webhook/__init__.py
- src/webhook/group_validation.py
- src/webhook/metrics.py
- src/webhook/subscription_validation.py
- templates/01-webhook.namespace.yaml.tmpl
- templates/02-prometheus-role-binding.yaml.tmpl
- templates/02-prometheus_role.yaml.tmpl
- templates/05-validation-webhook.service.yaml.tmpl
- templates/30-validation-webhook.servicemonitor.yaml.tmpl
Added following metrics:
1. webhook_subscription_validation - The total number of subscription validation requests
2. webhook_denied_subscription - The total number of subscription validation requests denied
3. webhook_group_validation - The total number of group validation requests
4. webhook_denied_group - The total number of group validation requests denied
> Expose metrics for validation webhooks

- templates/10-group-validation.ValidatingWebhookConfiguration.yaml.tmpl
This reverts commit 3cb81b5484692003697a8ab9e56fca12234c44ca.
See https://github.com/openshift/managed-cluster-validating-webhooks/pull/18
https://issues.redhat.com/browse/OSD-2573
> Revert "OSD-2573 Disable group WH in stage during"

- build/Dockerfile
Moving to a UBI image will ensure we have a better security footprint, as well as it will let us spin up CI on this repo (ref https://github.com/openshift/release/pull/7041).
I also switched around the order of the Dockerfile as well to improve build speed, as dependencies will be cached when doing local builds.
/cc @rogbas @csheremeta
> Base image off of ubi

- build/selectorsyncset.yaml
- templates/10-namespace-validation.ValidatingWebhookConfiguration.yaml.tmpl
- templates/10-regular-user-validation.ValidatingWebhookConfiguration.yaml.tmpl
https://issues.redhat.com/browse/OSD-2828
https://bugzilla.redhat.com/show_bug.cgi?id=1803956
Webhooks for Namespaces and denying access to users must fail open, i.e. policy = "Ignore", else cluster provisioning will fail if the webhook is not already online.  This race condition is happening a lot on OCP 4.4.0 rc builds.
> failurePolicy should be 'Ignore' or it causes cluster bring-up to fail

- src/webhook/regular_user_validation.py
"DELETE" action always failed with errors:
```
Exception:
------------------------------------------------------------
Traceback (most recent call last):
File "/app/webhook/regular_user_validation.py", line 34, in handle_request
kind = body_dict['object']['kind']
TypeError: 'NoneType' object is not subscriptable
10.129.0.1 - - [15/Apr/2020:08:48:53 +0000] "POST /regular-user-validation?timeout=30s HTTP/1.1" 200 154 "-" "kube-apiserver-admission" "pid=<14>"
```
> Fix bug for regular user validation

- build/pr_check.sh
Will catch if `build-sss` make target will change the generated selectorsyncset yaml.  If so, something is wrong.
> Update pr check to verify build-sss target is a noop

- src/webhook/namespace_validation.py
Corrects a small issue where the namespace webhook validation wasn't incrementing its denial counter when it should have.
> Added missing calls to namespace webhook denial counter

- Makefile
When `pwd` includes a symlink, the `test`, `build-sss` and `lint` make targets fail because even though the correct volume is mounted (with `-v` and using `pwd -P`), the "cd" inside the container does not respect it, and so will try to `cd` to the wrong place.
> :bug: When pwd involves a symlink, test, build-sss, lint fail

- build/build_deploy.sh
This is now causing builds to be problematic.
> OSD-4110: Remove IMAGE="$IMAGE" in build script

- build/selectorsyncset.yaml
- build/syncset.go
It should be rbac.authorization.k8s.io/v1, not v1.
> Fix bad APIVersion for ClusterRoleBinding

- pkg/webhooks/group/group_test.go
Adding explicit testing for osd-impersonators group, see openshift/managed-cluster-config#390
> Ensuring osd-impersonators group has regression tests

- build/syncset.go
Maps (aka associative arrays, aka dictionaries, aka hashes) have no
inherent sorting capabilities which means the resulting
selectorsyncset.yaml file is non-deterministic. Sorting the keys based
on name will result in a more deterministic run.
> Alphabetically sort syncsets

- build/selectorsyncset.yaml
https://issues.redhat.com/browse/OSD-4749
Refresh the list we deny which now includes managed-upgrade and splunkforwarder CRs.
Also fixes the apiGroup for managed-velero which is actually 'managed.openshift.io'.
> Update apiGroups denied to regular users

- pkg/webhooks/user/user_test.go
These are wrong, possibly from copy/paste error.
> Fix the gvk and gvr for user tests to User/users

- build/selectorsyncset.yaml
- pkg/webhooks/regularuser/regularuser.go
In #96 these were made in the YAML file, they are now moved to the code
file so that syncset.go will retain them in the future.
> OSD-4749: Move #96 changes to code

- Makefile
For some reason the dependencies have not been working correctly. Until they can be sussed out, treat it as a PHONY.
> Always build the syncset

- pkg/webhooks/user/user.go
- pkg/webhooks/user/user_test.go
Prior to the changes made in 92d168b446eb84b0284175164e524f483d092a46,
people could get a User account on cluster with an idp-group mismatch.
As part of the cleanup, we need to enable members of admin groups to
delete. This change fixes a bug with the cleanup
> OSD-4884: admin group members can delete users with IDP mismatch

- go.mod
- go.sum
* could not run steps: step managed-cluster-validating-webhooks failed: could not wait for build: the build managed-cluster-validating-webhooks failed after 4m13s with reason DockerBuildFailed: Dockerfile build strategy has failed.
github.com/openshift/library-go@v0.0.0-20200210105614-4bf528465627 requires
bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc...org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
> Fix bitbucket dependencies

- Makefile
with docker in Fedora 31/32
docker on F31 gives: `cgroups: cgroup mountpoint does not exist: unknown`
> Accommodate docker or podman in Makefile, to work around issues

- cmd/main.go
See: https://github.com/golang/go/issues/28308, https://github.com/dominikh/go-tools/issues/358 and others.
This could be seen as a bug, but we haven't hit any ipv6 issues yet, so this is an enhancement.
Note: Change made in GitHub's editor, which doesn't gofmt, so be gentle. ;)
> Use net.JoinHostPort over fmt.Sprintf

- build/selectorsyncset.yaml
- pkg/webhooks/add_pod.go
- pkg/webhooks/pod/pod.go
- pkg/webhooks/pod/pod_test.go
This commit adds in pod.go a webhook that will check the namespace in which the pods deploy, and if that namespace is openshift-logging, openshift-operators or a non-core namespace the deployment will not be allowed on master and infra nodes. This commit prevents the logging stack from targeting the infra nodes [OSD-4262](https://issues.redhat.com/browse/OSD-5269) and prevents customers from launching pods with workloads on master and infra JIRA ticket [OSD-4333](https://issues.redhat.com/browse/OSD-4333).
The unit tests for the pod webhook are in pod_test.go.
> Webhook for blocking pods in namespaces openshift-logging, openshift-operators and non-core mnamespaces from deploying on master and infra.

- pkg/webhooks/group/group.go
- pkg/webhooks/group/group_test.go
Reference: https://issues.redhat.com/browse/OSD-5378
This is my first pass at understanding this repo, so please let me know if I'm completely misunderstanding. 
What's the relation between this PR and this sheet? https://docs.google.com/spreadsheets/d/1sT3loQphcc75k3W3EKCcyeSTQ1ppK7Md7ASB0CUSOLQ/edit#gid=0
Should I be using the error messages from there instead? 
Another small question, what should be done with `osd-devaccess`?
> Split group checks between admin and managed groups

- README.md
- cmd/main.go
- pkg/dispatcher/dispatcher.go
- pkg/testutils/testutils.go
- pkg/webhooks/group/group.go
- pkg/webhooks/identity/identity.go
- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/pod/pod.go
- pkg/webhooks/register.go
- pkg/webhooks/regularuser/regularuser.go
- pkg/webhooks/subscription/subscription.go
- pkg/webhooks/user/user.go
This commit will remove the `HandleRequest` requirement and formalize
the heretofore informal `authorized` methods into the Webhook interface
by introducing a new dispatcher package that is responsible for parsing
the HTTP payload into a Request object that webhookscan deal more
natively with. Each hook, with this change, will shed any knowledge of
the transport mechanism and only work with the higher level logic
specifically around webhooks.
Also updated are documentation and testutils package to support these
new changes.
Misc bug fixes:
* HTTP Status is correctly written copied from the response object
(unless it was omitted from the object somehow) * Fixed some copy/paste
errors
fyi @cblecker @aliceh since if merged this will …
> DRY out HTTP request handling

- pkg/webhooks/group/group.go
- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/namespace/namespace_test.go
- pkg/webhooks/subscription/subscription_test.go
- pkg/webhooks/user/user.go
- pkg/webhooks/user/user_test.go
Feature
New layered product groups `rhoam-cs-sre-admins` and `rhoam-sre-cluster-admins` have been introduced to manage the RHOAM layered product [0] [1].
For the introduction of these groups to be of any use to CS-SRE admins, the admission webhooks would need to be aware of them as well. This PR adds support for the new `rhoam-*` groups, largely treating them the same as the `layered-*` group.
A business justification for the need to separate the existing `layered-*` from the new `rhoam-*` has been requested to be added to [OSD-5915](https://issues.redhat.com/browse/OSD-5915). This PR is just getting some work in ahead of time.
[OSD-5915](https://issues.redhat.com/browse/OSD-5915) 
[0] https://github.com/openshift/managed-cluster-config/pull/562
[1] …
> OSD-5915 support new RHOAM groups

- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/namespace/namespace_test.go
At the end of an e2e run, the last step is to collect must-gather, which
requires the creation of a namespace for that purpose. This alters the
namespace hook to allow osde2e service accounts to create that
namespace.
> OSD-5697: Allow osde2e ServiceAccounts to create must-gather ns

- build/syncset.go
- hack/documentation/document.go
- pkg/webhooks/group/group.go
- pkg/webhooks/identity/identity.go
- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/pod/pod.go
- pkg/webhooks/register.go
- pkg/webhooks/regularuser/regularuser.go
- pkg/webhooks/subscription/subscription.go
- pkg/webhooks/user/user.go
In support of [OSD-3296](https://issues.redhat.com/browse/OSD-3296)
Starting in Kubernetes 1.15, webhooks gained the ability to use a
LabelSelector to "limit which requests are intercepted" based on the
labels of objects that would be sent. This PR adds to the Webhook
interface an `ObjectSelector() *metav1.LabelSelector` method which will
support this. It is recommended to set to `nil` if the particular
webhook has no such ObjectSelector restrictions (so that the resulting
selectorsyncset.yaml file does not include an empty map, for clarity
sake).
> Add ObjectSelector support to Webhook interface

- README.md
Removal of the in-cluster object(s) is not handled by the deletion of code in this project, so it will need to be cleaned out by hand afterwards.
> Add Webhook removal note to delete the in-cluster objects

- pkg/webhooks/regularuser/regularuser.go
This slipped past and should have not been in the codebase.
> :bug: Remove extra debugging information

- pkg/webhooks/regularuser/regularuser.go
- pkg/webhooks/regularuser/regularuser_test.go
This will allow `CustomDomain` objects from `managed.openshift.io` to be
managed by members of the dedicated-admins group. This will also
slightly modify the logic of the `MustGather` section to refer to the
ApiGroup as well as the Kind (for future safety), and switch them to
being references to constants. Further, the check is done outside a loop
so it's a wee bit faster.
> OSD-6482: Dedicated-admins should be able to manage CustomDomain

- build/Dockerfile
registry.ci is the new image registry that replaces (old)registry.svc as per https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/. We can transition to use the new as the public images are supported and available by CI.
> fix: dockerfile image

- Makefile
- README.md
- Add some Makefile variables for more granular construction of the build image URI to facilitate simpler overriding for personal builds.
- Document the process to build, tag, push, and deploy a personal build to a personal cluster.
> Facilitate and document local test

- README.md
Change `\t` to `  `. In the Go code the `\t` is used (of course), but for readability in the README, `  ` is used so the indent isn't so much.
> Fix spacing issues in README.md

- build/build_push.sh
This started happening suddenly:
```
10:08:43 parse error: Invalid literal at line 1, column 6
10:08:43 Unexpected error: skopeo inspect succeeded, but output contained no .Digest
10:08:43 Here's the output:
10:08:43 time="2021-05-10T15:08:41Z" level=error msg="HEADER map[Content-Length:[185] Content-Type:[text/html] Date:[Mon, 10 May 2021 15:08:41 GMT] Server:[nginx/1.12.1]]"
10:08:43 {
10:08:43     "Name": "quay.io/app-sre/aws-account-operator",
10:08:43     "Digest": "sha256:02baefe6abe17a60f9751441fdd7223b3d79af5580639d4ea90285bbab28a0c7",
```
For some reason, `skopeo inspect` is now producing that header information on stderr, whereas it wasn't before.
Nevertheless, that's no excuse for glomming together stdout and stderr when we expect to be able to parse the former. So with this …
> Split out stderr for skopeo inspect

- .gitignore
- build/selectorsyncset.yaml
- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/regularuser/regularuser.go
- pkg/webhooks/regularuser/regularuser_test.go
This adds authorization for [NetNamespace](https://docs.openshift.com/container-platform/4.5/rest_api/network_apis/netnamespace-network-openshift-io-v1.html).
This also fixes up some test utils to allow for additional parameters such as Name and Namespace.
https://github.com/openshift/managed-cluster-config/pull/839 depends on this being merged first, such that dedicated-admins cannot update protected namespaces.
https://issues.redhat.com/browse/OSD-7367
> Authorize NetNamespace In Regular User Webhook

- pkg/helpers/response.go
- pkg/helpers/response_test.go
[Ref OSD-7327](https://issues.redhat.com/browse/OSD-7327)
- In an attempt to narrow the scope of ValidatingWebhookConfigurations Splunk alerts, I'm adding an owner label which can be filtered on in Splunk alerts. This is being done to avoid raising alerts to SREP for customer owned ValidatingWebhookConfigurations
> [OSD-7327] Apply owner label to resp.AuditAnnotations

- Makefile
- build/Dockerfile
This PR updates the golang images for managed-cluster-validating-webhooks to go 1.16. Additionally, it modifies the Makefile to copy [this stanza](https://github.com/openshift/boilerplate/blob/328a6a5330ca758439829122dbdfafca9dcc79cf/boilerplate/test/test-base-convention/standard.mk#L31-L38) from boilerplate make everything compatible with the openshift/release image, and the Dockerfile is slightly modified to download and cache the modules in a layer in order to improve build speed during development.
> Update golang images to 1.16

- README.md
- docs/webhooks-short.json
- docs/webhooks.json
Completes https://issues.redhat.com/browse/OSD-7740. 
Documentation for  managed-cluster-validating-webhooks can be generated using `make docs`; this PR captures the output so that the documentation is available without having to execute this command every time.
> OSD-7740 - Document all the components that are blocked by validating webhooks

- build/selectorsyncset.yaml
- docs/webhooks-short.json
- docs/webhooks.json
- pkg/webhooks/add_scc.go
- pkg/webhooks/scc/scc.go
- pkg/webhooks/scc/scc_test.go
add the webhook for scc with configurable allowed user and group
allow the service account for node-exporter by default
tested in live cluster that the webhook works well, and the upgrade can be finished without issue.
fixes: [OSD-9642](https://issues.redhat.com/browse/OSD-9642)
cc @NautiluX @Tessg22 @robotmaxtron
> add validation webhook for scc

- pkg/webhooks/namespace/namespace_test.go
Unit tests are expanded to cover the various scenarios around service accounts and privileged namespaces
> Expand tests for service accounts [OSD-9355]

- pkg/webhooks/scc/scc.go
pipelines-scc is managed by pipelines-operator, and it might be updated with the operator update
> remove pipelines-scc from the restricted list

- build/selectorsyncset.yaml
- pkg/webhooks/regularuser/regularuser.go
- pkg/webhooks/regularuser/regularuser_test.go
In the autoscaling.openshift.io apigroup, only restrict the clusterautoscalers and machineautoscalers resources.
Additionally, update the managed.openshift.io block using the provided command.
And lastly, fix some bugs in the tests
Fixes [OSD-10991](https://issues.redhat.com//browse/OSD-10991)
> Only block clusterautoscalers and machineautoscalers resources

- build/Dockerfile
I saw this while I was working on https://issues.redhat.com/browse/OSD-9791
Currently, the build fails on my local
```
make IMG_ORG=bseref build-base
/usr/bin/docker build -t quay.io/bseref/managed-cluster-validating-webhooks:f4474f7 -f /home/boran/go/src/github.com/managed-cluster-validating-webhooks/build/Dockerfile . && \
/usr/bin/docker tag quay.io/bseref/managed-cluster-validating-webhooks:f4474f7 quay.io/bseref/managed-cluster-validating-webhooks:latest
Sending build context to Docker daemon  1.404MB
Step 1/15 : FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10 AS builder
unauthorized: authentication required
make: *** [Makefile:82: build-image] Error 1
```
However, it works well and doesn't require auth if I update it to …
> ref: update the base image to a commonly used one

- pkg/webhooks/scc/scc.go
- pkg/webhooks/scc/scc_test.go
OCP 4.11 introduces additional Pod Security SCCs which act as the SCC defaults on new 4.11+ clusters. [0]
MCVW already has protection against user deletion of default SCCs; this PR adds the new SCCs to the list of defaults.
Refs [OSD-13025](https://issues.redhat.com//browse/OSD-13025)
[0] https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-auth-pod-security-admission
> Prevent deletion of new 4.11 SCCs

- README.md
Addresses [OSD-13325](https://issues.redhat.com/browse/OSD-13325), remediates CVE's found in the base image by rebuilding off the latest ubi-minimal.
> empty commit to trigger build of images for remediation

- pkg/webhooks/prometheusrule/prometheusrule.go
- pkg/webhooks/prometheusrule/prometheusrule_test.go
Adds an exception to the `prometheusrule` webhook to allow requests from the `openshift-monitoring` namespace so that the ACM addon can install and upgrade on OSD & ROSA clusters.
> Add exception to prometheusrule webhook for 'openshift-monitoring'

- pkg/webhooks/prometheusrule/prometheusrule.go
Adds an exception to the prometheusrule webhook to allow requests from the openshift-monitoring namespace so that the ACM addon can install and upgrade on OSD & ROSA clusters.
> Add exception to promethuesrule webhook for  openshift-monitoring NS

- hack/templates/00-managed-cluster-validating-webhooks-hs.SelectorSyncSet.yaml.tmpl
This corrects a small typo present in the Hypershift `managed-cluster-validating-webhooks` SelectorSyncSet that is preventing package-operator from installing the package.
> OSD-14741 Fix image typo in hypershift selectorsyncset

- pkg/webhooks/scc/scc.go
Bug
MCVW's `sre-scc-validation` webhook has been observed to block z-stream upgrades between 4.13.0-ec.3 and 4.13.0-rc.0 due to the update of the `hostnetwork-v2` SCC as part of that upgrade.
This PR updates the list of allowed users that can perform updates on SCCs to include `cluster-version-operator`'s service account.
[OSD-15725](https://issues.redhat.com//browse/OSD-15725)
> OSD-15725 prevent SCC webhook blocking CVO updates

- config/package/manifest.yaml
- config/package/resources.yaml.gotmpl
- hack/templates/00-managed-cluster-validating-webhooks-hs.SelectorSyncSet.yaml.tmpl
This PR is using new api of PKO to parameterizing Injection of caBundle of Management cluster to the Hosted cluster resource `ValidatingWebhookConfiguration`
Ref: https://package-operator.run/docs/concepts/object-template/
- Copy configmap `openshift-service-ca.crt`  value of `.data.service-ca\.crt` and inject into hosted cluster `ValidatingWebhookConfiguration`   `clientConfig.caBundle` which is deployed through PKO
> [Osd 15333 ] PKO to Inject caBundle of Management cluster to the Hosted cluster

- hack/templates/00-managed-cluster-validating-webhooks-hs.SelectorSyncSet.yaml.tmpl
The `{{ toJson ... }}` package-operator template currently being used in the MCVW `ObjectTemplate` resource is mistakenly being treated by ACM as an ACM policy template, causing the policy to not be applied.
This corrects that by adding an annotation which will prevent ACM from applying any templates to the resource. (which is fine, as there are no ACM templates being used in it)
Refs [OSD-15333](https://issues.redhat.com//browse/OSD-15333)
> Prevent ACM from acting on PKO templates

- .gitignore
- Makefile
- README.md
- build/selectorsyncset.yaml
- cmd/main.go
- go.mod
- pkg/testutils/testutils.go
- pkg/webhooks/add_imagecontentpolicies.go
- pkg/webhooks/imagecontentpolicies/imagecontentpolicies.go
- pkg/webhooks/imagecontentpolicies/imagecontentpolicies_test.go
- pkg/webhooks/register.go
- pkg/webhooks/utils/utils.go
[ImageContentPolicy](https://docs.openshift.com/container-platform/4.12/rest_api/config_apis/imagecontentpolicy-config-openshift-io-v1.html) and [ImageContentSourcePolicy](https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html) resources allow
customers to configure repository mirrors. This validating webhook will
prevent configuring mirrors for quay.io, registry.redhat.io, and
registry.access.redhat.com repositories as those will likely have an
adverse affect on managed OpenShift.
[OSD-15757](https://issues.redhat.com//browse/OSD-15757)
> Create new validating webhook for icp/icsp 

- pkg/webhooks/imagecontentpolicies/imagecontentpolicies.go
- pkg/webhooks/imagecontentpolicies/imagecontentpolicies_test.go
Due to recent findings in OSD-15757, teams are mirroring specific repos under registry.redhat.io
> Continue blocking registry.redhat.io exactly, but allow mirroring otherwise

- pkg/webhooks/imagecontentpolicies/imagecontentpolicies.go
- pkg/webhooks/imagecontentpolicies/imagecontentpolicies_test.go
This PR adds unit tests that would have caught the bugs that were fixed in #215 and #216
Of note is that GVK's need not be registered with the scheme because it marshals the object into `unstructured.Unstructured` under the hood and it passes the unit test!
[OSD-15757](https://issues.redhat.com//browse/OSD-15757)
> Unit test icp webhook validation and authorization

- build/resources.go
- build/selectorsyncset.yaml
- pkg/syncset/syncsetbylabelselector.go
Ensures that the `serviceAccount` and `serviceAccountName` fields are nullified in the `DaemonSet` that gets distributed by the SelectorSyncSet.
The removal of the ServiceAccount and associated references in [OSD-16717](https://issues.redhat.com//browse/OSD-16717) only worked partially, because the Hive ClusterSync does not remove the `serviceAccount` and `serviceAccountName` fields from the target Daemonset on the cluster. So it left them behind, whilst also deleting the `ServiceAccount`. Which means that pre-existing clusters in Staging are having a bad time.
To ensure that the fields properly get nullified on-cluster, we have to ensure they are set to empty-string in the SelectorSyncSet resource.
However, doing that is challenging, because these fields have `omitempty` set, so …
> OSD-16717 ensure serviceAccount fields are nullified

- pkg/webhooks/scc/scc.go
- pkg/webhooks/scc/scc_test.go
Allow the `system:admin` user to be able to UPDATE the default set of OpenShift SCCs.
The `cluster-version-operator` in HCP namespaces uses `system:admin` to patch SCCs during upgrades, rather than the regular OCP user of `system:serviceaccount:openshift-monitoring:cluster-monitoring-operator`.  This then gets blocked by MCVW and is causing y-stream upgrades to fail.
[OSD-16762](https://issues.redhat.com//browse/OSD-16762)
> OSD-16762 allow system:admin to update SCCs

- build/resources.go
- config/package/resources.yaml.gotmpl
Do not mount the API token into the `validation-webhooks` Deployment, as it is not necessary or used.
This change has been succesfully tested on HyperShift Hosted Clusters to verify that webhook protection still occurs.
Security hardening per [OSD-16717](https://issues.redhat.com//browse/OSD-16717)
> OSD-16717 Do not mount API token into MCVW pod

- pkg/webhooks/imagecontentpolicies/imagecontentpolicies.go
It was unclear that customers are able to configure mirrors for specific repositories and only blocked from configuring mirrors across the entirety of certain domains.
[OSD-15757](https://issues.redhat.com//browse/OSD-15757)
> Update ICP webhook documentation message

- Makefile
- build/Dockerfile
- cmd/fips.go
Feature
- Switch to golang 1.19 for building MCVW and the selectorsyncset resources.
- Ensure that MCVW runs with FIPS enabled so that it is consistent with other OSD operators and workloads.
> Enable FIPS and switch to golang-1.19

- build/selectorsyncset.yaml
- docs/webhooks-short.json
- docs/webhooks.json
- pkg/webhooks/add_ingresscontroller.go
- pkg/webhooks/ingresscontroller/ingresscontroller.go
- pkg/webhooks/ingresscontroller/ingresscontroller_test.go
This PR adds a webhook that inspects ingress controller creation request from customers. It blocks these requests when they have tolerations for infra and master nodes.
Issue: [OSD-16469](https://issues.redhat.com//browse/OSD-16469)
> OSD-16469 Block ingress controller provisioning on master and infra

- build/selectorsyncset.yaml
- config/package/resources.yaml.gotmpl
- docs/webhooks-short.json
- docs/webhooks.json
- pkg/webhooks/add_clusterrolebinding.go
- pkg/webhooks/clusterrolebinding/clusterrolebinding.go
- pkg/webhooks/clusterrolebinding/clusterrolebinding_test.go
Add the webhook for critical clusterrolebinding deletion prevention in following NS 
- openshift-*
- kube-system
> [OSD-16225] : Add clusterrolebinding webhooks to prevent deletion of clusterrolebings in openshift and kube-system namespace

- build/selectorsyncset.yaml
- config/package/resources.yaml.gotmpl
- docs/webhooks-short.json
- docs/webhooks.json
- pkg/testutils/testutils.go
- pkg/webhooks/add_serviceaccount.go
- pkg/webhooks/clusterlogging/clusterlogging_test.go
- pkg/webhooks/clusterrolebinding/clusterrolebinding_test.go
- pkg/webhooks/hiveownership/hiveownership_test.go
- pkg/webhooks/imagecontentpolicies/imagecontentpolicies_test.go
- pkg/webhooks/namespace/namespace_test.go
- pkg/webhooks/pod/pod.go
- pkg/webhooks/pod/pod_test.go
- pkg/webhooks/prometheusrule/prometheusrule_test.go
- pkg/webhooks/regularuser/common/regularuser_test.go
- pkg/webhooks/regularuser/osd/regularuser_test.go
- pkg/webhooks/scc/scc_test.go
- pkg/webhooks/serviceaccount/serviceaccount.go
- pkg/webhooks/serviceaccount/serviceaccount_test.go
- pkg/webhooks/techpreviewnoupgrade/techpreviewnoupgrade_test.go
Add the webhook for critical serviceccount deletion prevention
update the testutils to include the namespace value in the request
> [OSD-16224] add webhook to prevent critical serviceaccount deletion

- pkg/webhooks/serviceaccount/serviceaccount.go
- pkg/webhooks/serviceaccount/serviceaccount_test.go
Found a bug where the backplane-cluster-admin user and system users like kube:admin could not delete service accounts
> Allow kube and system users to delete service accounts

- pkg/webhooks/clusterrolebinding/clusterrolebinding.go
- pkg/webhooks/clusterrolebinding/clusterrolebinding_test.go
**Type**
Bug 
**Why ?**
SREP users and kube admin can't delete cluster role bindings in `openshift-*|kube-system` ns
> OSD-16225: Allow kube and system users to delete cluster role bindings

- build/selectorsyncset.yaml
- docs/webhooks-short.json
- docs/webhooks.json
- pkg/webhooks/add_ingresscontroller.go
- pkg/webhooks/ingresscontroller/ingresscontroller.go
- pkg/webhooks/ingresscontroller/ingresscontroller_test.go
This resolves [OSD-17439](https://issues.redhat.com//browse/OSD-17439)
The ingress controller webhook blocks non system, non authenticated users from provisioning ingress controllers on master and infra nodes.
A successful creation
```
I0712 13:15:24.454656       1 ingresscontroller.go:115] ingresscontroller-validation "msg"="Checking if user is unauthenticated" 
I0712 13:15:24.454670       1 ingresscontroller.go:125] ingresscontroller-validation "msg"="Checking if user is authenticated system: user" 
```
A blocked creation
```
I0712 13:11:55.259874       1 ingresscontroller.go:115] ingresscontroller-validation "msg"="Checking if user is unauthenticated" 
I0712 13:11:55.259890       1 ingresscontroller.go:125] ingresscontroller-validation "msg"="Checking if user is authenticated system: …
```
> OSD-16469 - Add ingress controller webhook

- Makefile
https://issues.redhat.com/browse/OSD-17665 - MCVW must be built with CGO_ENABLED=1 (and based on ubi-minimal) to be FIPS compliant
> CGO_ENABLED=1 to enable FIPS

- pkg/webhooks/clusterrolebinding/clusterrolebinding.go
Change made per: https://issues.redhat.com/browse/OSD-17844 to add openshift-gitops project as exception
> Added openshift-gitops project as an exception per request in OSD-17844

- README.md
- build/selectorsyncset.yaml
- pkg/webhooks/add_ingressconfig_hook.go
- pkg/webhooks/ingressconfig/ingressconfig.go
- pkg/webhooks/ingressconfig/ingressconfig_test.go
This webhook will prevent non-privileged serviceaccounts from creating, updating or deleting ingresses from config.openshift.io
Modifications to the cluster ingress config can degrade the authentication, console, and ingress operators
> OSD-18242 block customer modifying ingress config

- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/networkpolicies/networkpolicies.go
- pkg/webhooks/networkpolicies/networkpolicies_test.go
- pkg/webhooks/utils/utils.go
The regex was used in two places, so I centralized it within utils.go as well. I essentially added a `(h-)?` to the existing regex. This has been causing the osde2e test for OAO to consistently fail https://testgrid.k8s.io/redhat-openshift-ocp-release-4.14-informing#periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts 
Ref for why we need the optional `h-` (i.e. all decentralized osde2e tests will have this extra `h-` in the name): https://github.com/openshift/osde2e/blob/8202c6aae11848874aee554f733df5f44468e8f1/pkg/e2e/harness_runner/harness_runner.go#L52-L54
[OSD-20366](https://issues.redhat.com//browse/OSD-20366)
> Update regex to allow osde2e harness serviceaccount to be exempt

- Makefile
fixes error: lsetxattr when running make container-test
```
[tomas@ugnis-ocm managed-cluster-validating-webhooks]$ make container-test
/usr/bin/podman run \
-v /volumes/development/ugnis/src/github/openshift/managed-cluster-validating-webhooks:/volumes/development/ugnis/src/github/openshift/managed-cluster-validating-webhooks:z \
-w /volumes/development/ugnis/src/github/openshift/managed-cluster-validating-webhooks \
-e GOFLAGS= \
--rm \
registry.ci.openshift.org/openshift/release:golang-1.21 \
make test
Error: lsetxattr /volumes/development/ugnis/src/github/openshift/managed-cluster-validating-webhooks/.git: operation not supported
make: *** [Makefile:140: container-test] Error 126
```
> removes selinux label setting for make container-test

- pkg/webhooks/networkpolicies/networkpolicies.go
- pkg/webhooks/networkpolicies/networkpolicies_test.go
* UPDATE requests validated the OldObjects of the request
* OldObject is only used for update and delete requests, so when a new object exists it's always that which should be validated
Jira: [OSD-20308](https://issues.redhat.com//browse/OSD-20308)
> Networkpolicies: Fix UPDATE requests

- build/resources.go
- config/package/resources.yaml.gotmpl
This PR addresses bug [OSD-20871](https://issues.redhat.com/browse/OSD-20871), in which MCVW's HCP package failed to deploy on management clusters due to an extraneous reference to a service account. None of our HyperShift-enabled webhooks need access to the cluster's API, so this PR removes that reference.
> Remove ServiceAccount from packaged deployment

- cmd/main.go
This PR addresses bug [OSD-20871](https://issues.redhat.com/browse/OSD-20871) (also addressed by #284), in which MCVW's HCP package is failing to deploy on management clusters due to a failure to start the new metrics server. This failure occurs because the metrics server attempts to create a Service via the K8s API, but the default service account in use by the HCP package lacks permissions to do so. A future PR could introduce this Service by adding a resource to the generated package, but for now (in the interest of getting webhooks on HCP working again), this PR simply makes the failure-to-start-metrics error non-fatal (as there's no readiness/health check on HCP that would be making requests to the metrics Service anyways).
> Make failure-to-start-metrics non-fatal

- pkg/webhooks/ingresscontroller/ingresscontroller.go
- pkg/webhooks/ingresscontroller/ingresscontroller_test.go
Resolves [OSD-21358](https://issues.redhat.com/browse/OSD-21358), allowing scheduling of custom Ingress Controllers on infra nodes
> Allow customers to schedule custom Ingress Controllers on infra nodes

- pkg/webhooks/scc/scc.go
- pkg/webhooks/scc/scc_test.go
osde2e runs a conformance test which needs to be able to modify SCCs https://github.com/openshift/kubernetes/blob/e994e5dbd69833088514616351b0aa997e4ed79d/openshift-hack/e2e/namespace.go#L64-L71
This PR accomplishes this by adding a regexp for the osde2e group as a privileged group that can modify SCCs at will.
[OSD-22059](https://issues.redhat.com/browse/OSD-22059)
> Allow osde2e to modify SCCs

- build/selectorsyncset.yaml
- pkg/webhooks/regularuser/common/regularuser.go
This reverts commit 86f079d436973b8781157c1bd4e65d316845daa3, reversing changes made to 58448970c2f94cd0fd546ca349f7ee13f99ef3d4.
ref [OSD-22474](https://issues.redhat.com//browse/OSD-22474)
> Revert "Block changes to imageregistry.operator.openshift.io resources"

- pkg/webhooks/service/service.go
- pkg/webhooks/service/service_test.go
This PR addresses bug [OSD-21590](https://issues.redhat.com/browse/OSD-21590), in which the service-mutation webhook would sometimes allow users to modify or remove the `red-hat-managed=true` resource tag that's required for AWS managed policy compliance. This bug was caused by improper use of [AdmissionRequest.OldObject](https://pkg.go.dev/k8s.io/api/admission/v1#AdmissionRequest) within the mutating webhook's "object rendering" function `renderService()`. 
This PR fixes the bug by ignoring AdmissionRequest.OldObject entirely and always rendering AdmissionRequest.Object. It also adds unit tests that will catch any regressions on the bug.
> Fix improper rendering of Services in service-mutation webhook

- build/resources.go
- config/package/resources.yaml.gotmpl
- pkg/dispatcher/dispatcher.go
- pkg/k8sutil/k8sutil.go
- pkg/webhooks/podimagespec/podimagespec.go
Requires getting kubeconfig to the KAS for the HCP, not the cluster where the webbhook pod is running.
> Updated podimagespec to support HCP

- Makefile
- pkg/webhooks/regularuser/common/regularuser.go
* CI was failing because it was recently switched from docker to podman, this PR also fixes the root of the CI failures by SELinux relabling the volume mount when running `make container-test`
[OSD-24357](https://issues.redhat.com//browse/OSD-24357)
> Fix a harmless typo preventing clusterversion restrictions

- Makefile
- build/build_push.sh
- build/build_push_package.sh
* With the switch from docker to podman, just use podman to push instead of using skopeo to copy images from the docker socket
The last build failed https://ci.int.devshift.net/job/openshift-managed-cluster-validating-webhooks-gh-build-master/305/console:
```
11:02:51 skopeo copy --dest-creds "****:****" \
11:02:51 	"docker-daemon:quay.io/app-sre/managed-cluster-validating-webhooks:24539be" \
11:02:51 	"docker://quay.io/app-sre/managed-cluster-validating-webhooks:latest"
11:02:51 time="2024-07-09T15:02:51Z" level=fatal msg="initializing source docker-daemon:quay.io/app-sre/managed-cluster-validating-webhooks:24539be: loading image from docker engine: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get …
```
> Fix MCVW builds on RHEL8

- config/package/resources.yaml.gotmpl
- pkg/webhooks/imagecontentpolicies/imagecontentpolicies.go
- pkg/webhooks/imagecontentpolicies/imagecontentpolicies_test.go
This PR enable ECR image registry configuration on hosted clusters 
https://issues.redhat.com/browse/OSD-24266
> OSD-24266 : Disabled IDMS/ICSP validatingwebhook in HCP

- pkg/webhooks/prometheusrule/prometheusrule.go
https://issues.redhat.com/browse/OSD-13909
---
Reverts an exception in the `prometheusrule` webhook allowing anyone to create `prometheusrule` objects in the `openshift-monitoring` namespace now that [dependent components have been migrated out of the namespace](https://issues.redhat.com/browse/ACM-7631).
> OSD-13909 - Remove exception allowing prometheusrules to be created in `openshift-monitoring`

- README.md
Removes extraneous newlines at the end of the README.
Commit is primarily being submitted in order to trigger an automatic rebuild of the codebase, following the merge of https://github.com/openshift/release/pull/56782.
> Minor README.md cleanup

- build/Dockerfile
Reverts openshift/managed-cluster-validating-webhooks#320 and openshift/managed-cluster-validating-webhooks#321
These changes are causing the webhooks to crashloop in stage, blocking development work.
> Revert #320 and #321

- pkg/webhooks/namespace/namespace.go
Disable namespace webhook for HCP, see [OSD-25874](https://issues.redhat.com/browse/OSD-25874) for details
> [OSD-25874]Disable namespace webhook for HCP

- build/resources.go
- build/selectorsyncset.yaml
- Adding or fixing the maxUnavailable updateStrategy to match the OCP guidelines which is 10% or 33%.
- https://issues.redhat.com/browse/OSD-26323
> Added maxUnavailable to set to 10%

- osde2e/project.mk
https://issues.redhat.com/browse/OSD-27858
---
managed-cluster-validating-webhook changes are not being deployed to stage, as expected. The cause of this appears to be failing a failing make target (`e2e-image-build-push`) in Jenkins.
The make target is attempting to pull images from `http://quay.io/app-sre/validation-webhook-test-harness`, but the repository it should be pulling from is `quay.io/repository/app-sre/managed-cluster-validating-webhooks-test-harness`
> OSD-27858 - Fix osde2e test harness image name

- pkg/webhooks/sdnmigration/sdnmigration.go
- pkg/webhooks/sdnmigration/sdnmigration_test.go
When testing this via a hive sync I noticed it was failing. After further inspection of the certificate Hive uses, the `cn` was wrong. Looks like we took the value from the `Issuer`
```
Issuer: OU=openshift, CN=admin-kubeconfig-signer
Validity
Not Before: Jan 30 17:42:34 2025 GMT
Not After : Jan 28 17:42:34 2035 GMT
Subject: O=system:masters, CN=system:admin
```
> OSD-21711: Fix admin username that can bypass SDN webhook

- pkg/webhooks/prometheusrule/prometheusrule.go
- pkg/webhooks/prometheusrule/prometheusrule_test.go
[OSD-19341](https://issues.redhat.com/browse/OSD-19341)
Reverts an exception in the `prometheusrule webhook` allowing anyone to create `prometheusrule` objects in the `openshift-customer-monitoring` & `openshift-user-workload-monitoring` namespace. The exception was created to unblock APP-SRE migration workload monitoring off of openshift-customer-monitoring (https://issues.redhat.com/browse/APPSRE-6523 / [OSD-13680](https://issues.redhat.com/browse/OSD-13680))
> [OSD-19341] Remove exception allowing prometheusrules to be created in 'openshift-customer-monitoring' & 'openshift-user-workload-monitoring'

- test/e2e/managed_cluster_validating_webhooks_test.go
https://issues.redhat.com/browse/OSD-28343
This has been tested extensively, running both the full suite and individual tests that were previously failing to ensure that there is no flakiness.
In addition, it cleans up the test pod, the webhook-sa test sa and the test namespace that hadn't been cleaned up and would still be in the cluster after test runs.
> Ensure namespace is created before creating any cluster resources

- pkg/webhooks/scc/scc.go
- pkg/webhooks/scc/scc_test.go
https://issues.redhat.com/browse/OSD-28850
---
Adds the `openshift-kube-apiserver-operator`'s serviceaccount to the SCC webhook's allowlist, granting the kube-apiserver-operator the ability to freely manage SCCs without SRE interference.
> OSD-28850 - add the openshift-kube-apiserver-operator serviceaccount to the SCC allowlist

- pkg/webhooks/prometheusrule/prometheusrule.go
- pkg/webhooks/prometheusrule/prometheusrule_test.go
Reverting https://github.com/openshift/managed-cluster-validating-webhooks/pull/349 change, App SRE still uses the openshift-customer-monitoring ns and removing the exception cause [errors](https://console-openshift-console.apps.rosa.appsrep09ue1.03r5.p3.openshiftapps.com/k8s/ns/app-interface-production/pods/qontract-reconcile-openshift-prometheus-rules-1-5595c6dbb79r2n6/logs) and blocking https://issues.redhat.com/browse/ASIC-629
[OHSS-43133](https://issues.redhat.com/browse/OHSS-43133)
> Add exception for openshift-customer-monitoring for the PrometheusRule webhook

- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/namespace/namespace_test.go
https://issues.redhat.com/browse/SREP-1565
---
Removes an exception in the namespaces webhook which allows members of the cluster-admins group, the group customer users are added to when granted cluster-admin privileges in OCM, to modify platform-namespaces and privileged labels which can impact their SLA. It does not impact `backplane-cluster-admin` group members nor `layered-sre-cluster-admins`.
> SREP-1565 - Remove cluster-admins exception from namespaces webhook

- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/namespace/namespace_test.go
Reverts openshift/managed-cluster-validating-webhooks#387 due to [failing CI jobs](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.20-e2e-rosa-sts-ovn/1957627802882674688)
> Revert "SREP-1565 - Remove cluster-admins exception from namespaces webhook"

- pkg/webhooks/namespace/namespace.go
- pkg/webhooks/namespace/namespace_test.go
https://issues.redhat.com/browse/SREP-1770
---
Adds an explicit exception to the managed-cluster-validating-webhooks which allows the nvidia-gpu-operator to manage labels on unprotected namespaces. 
This exception is limited to the `gpu-operator` serviceaccount in the `nvidia-gpu-operator` namespace. While OperatorHub allows the operator to be installed into any project, [Nvidia docs](https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/install-gpu-ocp.html#installing-the-nvidia-gpu-operator-by-using-the-web-console) indicate this label is only added by the operator when installed in that namespace.
Changes were validated by installing the operator via OperatorHub, [creating a ClusterPolicy CR](https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/install-gpu-ocp.htm …
> SREP-1770 - Allow nvidia-gpu-operator to label unprotected namespaces with `openshift.io/cluster-monitoring: "true"`
